from dataclasses import dataclass
from typing import Optional
from afwip.core.constants import TokenType, BandID, TokenScoreType

@dataclass(frozen=True)
class TokenProfile:
    # Identity
    token_type: TokenType
    token_count: int 
    token_score_type: TokenScoreType

    # Bands Info 
    spawn_bands: frozenset[BandID]
    movement_bands: frozenset[BandID]

    # Movement
    move_range: int

    # Acquisition
    acquire_range: Optional[int]
    acquire_bonus: Optional[int]        # default 0
    acquire_rolls: int       # default 1; AEW = 2

    # Enemy Acquisition
    acquisition_value: int  # minimum roll needed for enemy to acquire this token

    # Air attack
    air_atk_range: Optional[int]
    air_atk_thresh: Optional[int]

    # Surface attack
    surf_atk_range: Optional[int]
    surf_atk_thresh: Optional[int]
    surf_exploding_die: bool

    # Missile defense
    has_missile_defense: bool

    # Naval salvos
    air_salvos: Optional[int]
    surf_salvos: Optional[int]

    # Winchester
    winchester_threshold: Optional[int] # 4 standard, 3 Attack UAS

    # Surface combatant 
    surface_combatant: bool


TOKEN_REGISTRY: dict[TokenType, TokenProfile] = {
    TokenType.F_22: TokenProfile(
        token_type = TokenType.F_22,
        token_count = 4,
        token_score_type=TokenScoreType.FIGHTER,
        spawn_bands = frozenset({BandID.BAND_A}),
        movement_bands= frozenset({BandID.US_AIRBASE, BandID.US_CONTINGENCY_LOCATION, BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 2,
        acquire_range = 2,
        acquire_bonus = 1,
        acquire_rolls = 1,
        acquisition_value = 4,
        air_atk_range = 1,
        air_atk_thresh = 2,
        surf_atk_range = None,
        surf_atk_thresh = None,
        surf_exploding_die = False,
        has_missile_defense = False,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = 4,
        surface_combatant=False
    ), 
    TokenType.F_35A: TokenProfile(
        token_type = TokenType.F_35A,
        token_count = 4,
        token_score_type=TokenScoreType.FIGHTER,
        spawn_bands = frozenset({BandID.BAND_A}),
        movement_bands= frozenset({BandID.US_AIRBASE, BandID.US_CONTINGENCY_LOCATION, BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 2,
        acquire_range = 2,
        acquire_bonus = 0,
        acquire_rolls = 1,
        acquisition_value = 4,
        air_atk_range = 1,
        air_atk_thresh = 2,
        surf_atk_range = 1,
        surf_atk_thresh = 2,
        surf_exploding_die = False,
        has_missile_defense = False,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = 4,
        surface_combatant=False
    ), 
    TokenType.F_15E: TokenProfile(
        token_type = TokenType.F_15E,
        token_score_type=TokenScoreType.FIGHTER,
        token_count = 4,
        spawn_bands = frozenset({BandID.BAND_A}),
        movement_bands= frozenset({BandID.US_AIRBASE, BandID.US_CONTINGENCY_LOCATION, BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 2,
        acquire_range = 2,
        acquire_bonus = 0,
        acquire_rolls = 1,
        acquisition_value = 2,
        air_atk_range = 1,
        air_atk_thresh = 2,
        surf_atk_range = 1,
        surf_atk_thresh = 2,
        surf_exploding_die = False,
        has_missile_defense = False,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = 4,
        surface_combatant=False
    ),
    TokenType.F_15C: TokenProfile(
        token_type = TokenType.F_15C,
        token_count = 4,
        token_score_type=TokenScoreType.FIGHTER,
        spawn_bands = frozenset({BandID.BAND_A}),
        movement_bands= frozenset({BandID.US_AIRBASE, BandID.US_CONTINGENCY_LOCATION, BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 2,
        acquire_range = 2,
        acquire_bonus = 0,
        acquire_rolls = 1,
        acquisition_value = 2,
        air_atk_range = 1,
        air_atk_thresh = 2,
        surf_atk_range = None,
        surf_atk_thresh = None,
        surf_exploding_die = False,
        has_missile_defense = False,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = 4,
        surface_combatant=False
    ),
    TokenType.F_16C: TokenProfile(
        token_type = TokenType.F_16C,
        token_count = 4,
        token_score_type= TokenScoreType.FIGHTER,
        spawn_bands = frozenset({BandID.BAND_A}),
        movement_bands= frozenset({BandID.US_AIRBASE, BandID.US_CONTINGENCY_LOCATION, BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 2,
        acquire_range = 2,
        acquire_bonus = 0,
        acquire_rolls = 1,
        acquisition_value = 2,
        air_atk_range = 1,
        air_atk_thresh = 3,
        surf_atk_range = 1,
        surf_atk_thresh = 2,
        surf_exploding_die = False,
        has_missile_defense = False,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = 4,
        surface_combatant=False
    ),
    TokenType.B_52: TokenProfile(
        token_type = TokenType.B_52,
        token_count = 1,
        token_score_type = TokenScoreType.BOMBER,
        spawn_bands = frozenset({BandID.BAND_A, BandID.US_STANDOFF}),
        movement_bands= frozenset({BandID.US_AIRBASE, BandID.US_CONTINGENCY_LOCATION, BandID.US_STANDOFF, BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 1,
        acquire_range = 2,
        acquire_bonus = 0,
        acquire_rolls = 1,
        acquisition_value = 2,
        air_atk_range = None,
        air_atk_thresh = None,
        surf_atk_range = 6,
        surf_atk_thresh = 2,
        surf_exploding_die = True,
        has_missile_defense = False,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = 4,
        surface_combatant=False
    ),
    TokenType.EC_130: TokenProfile(
        token_type = TokenType.EC_130,
        token_score_type = TokenScoreType.EC_130,
        token_count = 1,
        spawn_bands = frozenset({BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        movement_bands= frozenset({BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 1,
        acquire_range = None,
        acquire_bonus = 0,
        acquire_rolls = 1,
        acquisition_value = 3,
        air_atk_range = None,
        air_atk_thresh = None,
        surf_atk_range = None,
        surf_atk_thresh = None,
        surf_exploding_die = False,
        has_missile_defense = False,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = None,
        surface_combatant=False
    ),
    TokenType.DDG_115: TokenProfile(
        token_type = TokenType.DDG_115,
        token_count = 1,
        token_score_type=TokenScoreType.SHIP,
        spawn_bands = frozenset({BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        movement_bands= frozenset({BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 1,
        acquire_range = 2,
        acquire_bonus = 1,
        acquire_rolls = 1,
        acquisition_value = 2,
        air_atk_range = 3,
        air_atk_thresh = 2,
        surf_atk_range = 3,
        surf_atk_thresh = 2,
        surf_exploding_die = True,
        has_missile_defense = True,
        air_salvos = 4,
        surf_salvos = 1,
        winchester_threshold = None,
        surface_combatant=True
    ),
    TokenType.DDG_81: TokenProfile(
        token_type = TokenType.DDG_81,
        token_count = 1,
        token_score_type = TokenScoreType.SHIP,
        spawn_bands = frozenset({BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        movement_bands= frozenset({BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 1,
        acquire_range = 2,
        acquire_bonus = 1,
        acquire_rolls = 1,
        acquisition_value = 2,
        air_atk_range = 3,
        air_atk_thresh = 2,
        surf_atk_range = 3,
        surf_atk_thresh = 2,
        surf_exploding_die = True,
        has_missile_defense = True,
        air_salvos = 4,
        surf_salvos = 1,
        winchester_threshold = None,
        surface_combatant=True
    ),
    TokenType.ADA_US: TokenProfile(
        token_type = TokenType.ADA_US,
        token_count = 1,
        token_score_type = TokenScoreType.ADA,
        spawn_bands = frozenset({BandID.US_AIRBASE, BandID.US_CONTINGENCY_LOCATION}),
        movement_bands= frozenset(),
        move_range = 0,
        acquire_range = 2,
        acquire_bonus = 1,
        acquire_rolls = 1,
        acquisition_value = 2,
        air_atk_range = 1,
        air_atk_thresh = 2,
        surf_atk_range = None,
        surf_atk_thresh = None,
        surf_exploding_die = False,
        has_missile_defense = True,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = None,
        surface_combatant=False
    ),
    TokenType.AEW_US: TokenProfile(
        token_type = TokenType.AEW_US,
        token_count = 1,
        token_score_type=TokenScoreType.AEW,
        spawn_bands = frozenset({BandID.BAND_A, BandID.US_STANDOFF}),
        movement_bands = frozenset({BandID.US_AIRBASE, BandID.US_CONTINGENCY_LOCATION, BandID.US_STANDOFF, BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 1,
        acquire_range = 3,
        acquire_bonus = 2,
        acquire_rolls = 2,
        acquisition_value = 2,
        air_atk_range = None,
        air_atk_thresh = None,
        surf_atk_range = None,
        surf_atk_thresh = None,
        surf_exploding_die = False,
        has_missile_defense = False,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = None,
        surface_combatant=False
    ),
    TokenType.ATTACK_UAS_US: TokenProfile(
        token_type = TokenType.ATTACK_UAS_US,
        token_count = 4,
        token_score_type=TokenScoreType.UAS,
        spawn_bands = frozenset({BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        movement_bands= frozenset({BandID.US_AIRBASE, BandID.US_CONTINGENCY_LOCATION, BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 1,
        acquire_range = 2,
        acquire_bonus = 0,
        acquire_rolls = 1,
        acquisition_value = 3,
        air_atk_range = None,
        air_atk_thresh = None,
        surf_atk_range = 1,
        surf_atk_thresh = 3,
        surf_exploding_die = False,
        has_missile_defense = False,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = 3,
        surface_combatant=False
    ),
    TokenType.RECON_UAS_US: TokenProfile(
        token_type = TokenType.RECON_UAS_US,
        token_count = 2,
        token_score_type=TokenScoreType.UAS,
        spawn_bands = frozenset({BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        movement_bands= frozenset({BandID.US_AIRBASE, BandID.US_CONTINGENCY_LOCATION, BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 1,
        acquire_range = 2,
        acquire_bonus = 1,
        acquire_rolls = 2,
        acquisition_value = 3,
        air_atk_range = None,
        air_atk_thresh = None,
        surf_atk_range = None,
        surf_atk_thresh = None,
        surf_exploding_die = False,
        has_missile_defense = False,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = None,
        surface_combatant=False
    ),
    TokenType.J_20B: TokenProfile(
        token_type = TokenType.J_20B,
        token_count = 4,
        token_score_type=TokenScoreType.FIGHTER,
        spawn_bands = frozenset({BandID.BAND_E}),
        movement_bands = frozenset({BandID.PRC_AIRBASE, BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 2,
        acquire_range = 2,
        acquire_bonus = 1,
        acquire_rolls = 1,
        acquisition_value = 4,
        air_atk_range = 1,
        air_atk_thresh = 2,
        surf_atk_range = None,
        surf_atk_thresh = None,
        surf_exploding_die = False,
        has_missile_defense = False,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = 4,
        surface_combatant=False
    ),
    TokenType.JH_7: TokenProfile(
        token_type = TokenType.JH_7,
        token_count = 4,
        token_score_type=TokenScoreType.FIGHTER,
        spawn_bands = frozenset({BandID.BAND_E}),
        movement_bands = frozenset({BandID.PRC_AIRBASE, BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 2,
        acquire_range = 2,
        acquire_bonus = 0,
        acquire_rolls = 1,
        acquisition_value = 2,
        air_atk_range = 1,
        air_atk_thresh = 3,
        surf_atk_range = 1,
        surf_atk_thresh = 2,
        surf_exploding_die = False,
        has_missile_defense = False,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = 4,
        surface_combatant=False
    ),
    TokenType.J_10: TokenProfile(
        token_type = TokenType.J_10,
        token_count = 4,
        token_score_type=TokenScoreType.FIGHTER,
        spawn_bands = frozenset({BandID.BAND_E}),
        movement_bands = frozenset({BandID.PRC_AIRBASE, BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 2,
        acquire_range = 2,
        acquire_bonus = 0,
        acquire_rolls = 1,
        acquisition_value = 2,
        air_atk_range = 1,
        air_atk_thresh = 3,
        surf_atk_range = 1,
        surf_atk_thresh = 2,
        surf_exploding_die = False,
        has_missile_defense = False,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = 4,
        surface_combatant=False
    ),
    TokenType.J_15: TokenProfile(
        token_type = TokenType.J_15,
        token_count = 4,
        token_score_type=TokenScoreType.FIGHTER,
        spawn_bands = frozenset({BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        movement_bands = frozenset({BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 2,
        acquire_range = 2,
        acquire_bonus = 0,
        acquire_rolls = 1,
        acquisition_value = 2,
        air_atk_range = 1,
        air_atk_thresh = 2,
        surf_atk_range = 1,
        surf_atk_thresh = 2,
        surf_exploding_die = False,
        has_missile_defense = False,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = 4,
        surface_combatant=False
    ),
    TokenType.J_16: TokenProfile(
        token_type = TokenType.J_16,
        token_count = 4,
        token_score_type=TokenScoreType.FIGHTER,
        spawn_bands = frozenset({BandID.BAND_E}),
        movement_bands = frozenset({BandID.PRC_AIRBASE, BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 2,
        acquire_range = 2,
        acquire_bonus = 0,
        acquire_rolls = 1,
        acquisition_value = 2,
        air_atk_range = 1,
        air_atk_thresh = 2,
        surf_atk_range = 1,
        surf_atk_thresh = 2,
        surf_exploding_die = False,
        has_missile_defense = False,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = 4,
        surface_combatant=False
    ),
    TokenType.H_6K: TokenProfile(
        token_type = TokenType.H_6K,
        token_count = 1,
        token_score_type=TokenScoreType.BOMBER,
        spawn_bands = frozenset({BandID.BAND_E, BandID.PRC_STANDOFF}),
        movement_bands = frozenset({BandID.PRC_AIRBASE, BandID.PRC_STANDOFF, BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 1,
        acquire_range = 2,
        acquire_bonus = 0,
        acquire_rolls = 1,
        acquisition_value = 2,
        air_atk_range = None,
        air_atk_thresh = None,
        surf_atk_range = 6,
        surf_atk_thresh = 2,
        surf_exploding_die = True,
        has_missile_defense = False,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = 4,
        surface_combatant=False
    ),
    TokenType.MID_RANGE_ADA_PRC: TokenProfile(
        token_type = TokenType.MID_RANGE_ADA_PRC,
        token_count = 1,
        token_score_type=TokenScoreType.ADA,
        spawn_bands = frozenset({BandID.PRC_AIRBASE}),
        movement_bands= frozenset(),
        move_range = 0,
        acquire_range = 2,
        acquire_bonus = 1,
        acquire_rolls = 1,
        acquisition_value = 2,
        air_atk_range = 1,
        air_atk_thresh = 2,
        surf_atk_range = None,
        surf_atk_thresh = None,
        surf_exploding_die = False,
        has_missile_defense = True,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = None,
        surface_combatant=False
    ),
    TokenType.LONG_RANGE_ADA_PRC: TokenProfile(
        token_type = TokenType.LONG_RANGE_ADA_PRC,
        token_count = 1,
        token_score_type=TokenScoreType.ADA,
        spawn_bands = frozenset({BandID.PRC_AIRBASE}),
        movement_bands= frozenset(),
        move_range = 0,
        acquire_range = 2,
        acquire_bonus = 1,
        acquire_rolls = 1,
        acquisition_value = 2,
        air_atk_range = 3,
        air_atk_thresh = 2,
        surf_atk_range = None,
        surf_atk_thresh = None,
        surf_exploding_die = False,
        has_missile_defense = True,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = None,
        surface_combatant=False
    ),
    TokenType.NANNING_162: TokenProfile(
        token_type = TokenType.NANNING_162,
        token_count = 1,
        token_score_type=TokenScoreType.SHIP,
        spawn_bands = frozenset({BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        movement_bands = frozenset({BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 1,
        acquire_range = 2,
        acquire_bonus = 1,
        acquire_rolls = 1,
        acquisition_value = 2,
        air_atk_range = 3,
        air_atk_thresh = 2,
        surf_atk_range = 3,
        surf_atk_thresh = 2,
        surf_exploding_die = True,
        has_missile_defense = True,
        air_salvos = 4,
        surf_salvos = 1,
        winchester_threshold = None,
        surface_combatant=True
    ),
    TokenType.DALIAN_105: TokenProfile(
        token_type = TokenType.DALIAN_105,
        token_count = 1,
        token_score_type=TokenScoreType.SHIP,
        spawn_bands = frozenset({BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        movement_bands = frozenset({BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 1,
        acquire_range = 2,
        acquire_bonus = 1,
        acquire_rolls = 1,
        acquisition_value = 2,
        air_atk_range = 3,
        air_atk_thresh = 2,
        surf_atk_range = 3,
        surf_atk_thresh = 2,
        surf_exploding_die = True,
        has_missile_defense = True,
        air_salvos = 4,
        surf_salvos = 1,
        winchester_threshold = None,
        surface_combatant=True
    ),
    TokenType.FLOTILLA: TokenProfile(
        token_type = TokenType.FLOTILLA,
        token_count = 1,
        token_score_type=TokenScoreType.SHIP,
        spawn_bands = frozenset({BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        movement_bands = frozenset({BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 1,
        acquire_range = 2,
        acquire_bonus = 0,
        acquire_rolls = 1,
        acquisition_value = 3,
        air_atk_range = None,
        air_atk_thresh = None,
        surf_atk_range = 2,
        surf_atk_thresh = 3,
        surf_exploding_die = True,
        has_missile_defense = False,
        air_salvos = None,
        surf_salvos = 1,
        winchester_threshold = None,
        surface_combatant=True
    ),
    TokenType.AEW_PRC: TokenProfile(
        token_type = TokenType.AEW_PRC,
        token_count = 1,
        token_score_type=TokenScoreType.AEW,
        spawn_bands = frozenset({BandID.BAND_E, BandID.PRC_STANDOFF}),
        movement_bands = frozenset({BandID.PRC_AIRBASE, BandID.PRC_STANDOFF, BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 1,
        acquire_range = 3,
        acquire_bonus = 2,
        acquire_rolls = 2,
        acquisition_value = 2,
        air_atk_range = None,
        air_atk_thresh = None,
        surf_atk_range = None,
        surf_atk_thresh = None,
        surf_exploding_die = False,
        has_missile_defense = False,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = None,
        surface_combatant=False
    ),
    TokenType.ATTACK_UAS_PRC: TokenProfile(
        token_type = TokenType.ATTACK_UAS_PRC,
        token_count = 4,
        token_score_type=TokenScoreType.UAS,
        spawn_bands = frozenset({BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        movement_bands = frozenset({BandID.PRC_AIRBASE, BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 1,
        acquire_range = 2,
        acquire_bonus = 0,
        acquire_rolls = 1,
        acquisition_value = 3,
        air_atk_range = None,
        air_atk_thresh = None,
        surf_atk_range = 1,
        surf_atk_thresh = 3,
        surf_exploding_die = False,
        has_missile_defense = False,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = 3,
        surface_combatant=False
    ),
    TokenType.RECON_UAS_PRC: TokenProfile(
        token_type = TokenType.RECON_UAS_PRC,
        token_count = 2,
        token_score_type=TokenScoreType.UAS,
        spawn_bands = frozenset({BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        movement_bands = frozenset({BandID.PRC_AIRBASE, BandID.BAND_A, BandID.BAND_B, BandID.BAND_C, BandID.BAND_D, BandID.BAND_E}),
        move_range = 1,
        acquire_range = 2,
        acquire_bonus = 1,
        acquire_rolls = 2,
        acquisition_value = 3,
        air_atk_range = None,
        air_atk_thresh = None,
        surf_atk_range = None,
        surf_atk_thresh = None,
        surf_exploding_die = False,
        has_missile_defense = False,
        air_salvos = None,
        surf_salvos = None,
        winchester_threshold = None,
        surface_combatant=False
    )
}


